### ISSUE TITLE
Errors importing SCTK v30.1.0 Scans

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/scancode-workbench#507]
When importing a -clipeu Scan created with SCTK v30.1.0, the import from JSON fails with 3 errors and 1 warning:

The errors are:

Uncaught (in promise) DatabaseError: SQLITE_ERROR: no such table: flat_files
    at Query.formatError (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\query.js:423:16)
    at afterExecute (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\query.js:119:32)
    at replacement (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.errBack (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\sqlite3\lib\sqlite3.js:16:21)

The warning is:

_C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:883 Unhandled rejection TypeError: Right-hand side of 'instanceof' is not an object
    at workbenchDB.sync.then.then.then.then.then.catch (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\assets\app\js\renderer.js:435:21)
    at tryCatcher (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\promise.js:695:18)
    at _drainQueueStep (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\async.js:147:5)
    at Async.drainQueues (C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
printWarning @ C:\ABOUTCODE\releases\ScanCode-Workbench-windows-x64-3.1.1.post17.ee52d6f\resources\app.asar\node_modules\bluebird\js\release\debuggability.js:883_

There are no problems with a --info Scan of the same codebase with SCTK v30.1.0. Could the errors may be related to changes in the schema for Package data? I have not yet tried a -clieu Scan for this codebase.

The SCWB version is 3.1.1

**Comment by AyanSinhaMahapatra** [comment]
This is now obsolete, as we are at v4.0.0rc2 and supporting SCTK v32.x only, closing this!
